echo "######################################################"
echo "#      欢迎使用组学大讲堂提供的docker镜像            #"
echo "#      问题交流请访问：www.omicsclass.com            #"
echo "######################################################"
echo ""
echo "            Linux新手建议学习课程："
echo "      --> https://www.omicsclass.com/article/702"
echo ""
echo "         搭建实验室生信分析平台与docker使用详情见课程："
echo "      --> https://www.omicsclass.com/article/1181"
echo ""
echo "           更多组学大讲堂生物信息分析课程："
echo "      --> https://www.omicsclass.com/article/129"
echo ""
echo "本镜像用于BSA分析-继承自基因组重测序数据分析-学习使用课程推荐："
echo "--> https://study.163.com/course/introduction/1210221805.htm?share=1&shareId=1030291076"

