echo "######################################################"
echo "#      欢迎使用组学大讲堂提供的docker镜像            #"
echo "#      问题交流请访问：www.omicsclass.com            #"
echo "######################################################"
echo ""
echo "            Linux新手建议学习课程："
echo "	        https://zzw.h5.xeknow.com/s/17gwqZ"
echo "         搭建实验室生信分析平台与docker使用详情见课程："
echo "      --> https://zzw.h5.xeknow.com/s/36eLx5"
echo ""
echo "           更多组学大讲堂生物信息分析课程："
echo "      --> https://study.omicsclass.com/index"
echo ""
echo "        本镜像用于单细胞数据分析推荐学习课程："
echo "      --> https://zzw.h5.xeknow.com/s/4i88K6 "
