name: base
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=3.7
- blast=2.9.0
- matplotlib=3.1.0
- perl=5.26.2
- r-base=3.6
- r-ggplot2=3.2.1
- circos=0.69.8
- bedtools=2.29.2
- vcftools=0.1.16
- plink=1.90b6.12
- r-cmplot=3.6.2
- admixture=1.3.0
- r-optparse=1.6.4
- indexed_gzip=1.2.0
- bcftools=1.10.2
- samtools=1.10
- r-getopt 
- bioconductor-multtest 
- bioconductor-snpstats 
- r-scatterplot3d 
- r-genetics 
- r-ape 
- r-gplots 
- r-emmreml 
