name: ampliseq-q1
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- python=2.7
- qiime=1.9.1
- mothur
- mock
- nose
- fastq-join
- fastp
#- vsearch=2.14.2
- fastqc
## QIIME2 2019/10
##- bioconductor-iranges=2.16.0
##- bioconductor-rsamtools=1.34.0
##- bioconductor-s4vectors=0.20.1
##- bioconductor-shortread=1.40.0
##- bioconductor-summarizedexperiment=1.12.0
##- bioconductor-xvector=0.22.0
##- biom-format=2.1.7
##- blas=2.14
##- blast=2.9.0
##- fastcluster=1.1.25
##- fasttree=2.1.10
##- iqtree=1.6.12
##- matplotlib=2.2.4
##- numpy
##- perl-bioperl=1.7.2
##- pip
##- pyparsing=2.3.1
##- pyqt=5.9.2
##- pyrsistent=0.15.5
##- qt=5.9.7
- r-base=3.6
- r-getopt
##- r-cluster=2.1.0
##- r-data.table=1.12.6
##- r-digest=0.6.22
- r-ggplot2
##- r-glue=1.3.1
##- r-gtable=0.3.0
##- r-lattice=0.20_38
##- r-latticeextra=0.6_28
##- r-magrittr=1.5
##- r-mass=7.3_51.4
##- r-matrix=1.2_17
##- r-matrixstats=0.55.0
##- r-mgcv=1.8_29
##- r-munsell=0.5.0
##- r-nlme=3.1_141
##- r-permute=0.9_5
##- r-pillar=1.4.2
##- r-pkgconfig=2.0.3
##- r-plyr=1.8.4
##- r-r6=2.4.0
##- r-rcolorbrewer=1.1_2
##- r-rcpp=1.0.2
##- r-rcppparallel=4.4.4
##- r-rcurl=1.95_4.12
##- r-reshape2=1.4.3
##- r-rlang=0.4.1
##- r-scales=1.0.0
##- r-snow=0.4_3
##- r-stringi=1.4.3
##- r-stringr=1.4.0
##- r-tibble=2.1.3
##- r-utf8=1.1.4
- r-vegan
##- scipy
##- six=1.13.0
