name: base
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- r-rmarkdown=1.18
- bioconductor-biobase=2.42.0
- bioconductor-biocgenerics=0.28.0
- bioconductor-biocparallel=1.16.6
- bioconductor-biostrings=2.50.2
- bioconductor-genomeinfodb=1.18.1
- bioconductor-genomeinfodbdata=1.2.1
- bioconductor-genomicalignments=1.18.1
- bioconductor-genomicranges=1.34.0
- bioconductor-iranges=2.16.0
- bioconductor-s4vectors=0.20.1
- blast=2.9.0
- fasttree=2.1.10
- future=0.18.2
- iqtree=1.6.12
- mafft=7.310
- matplotlib=3.1.0
- matplotlib-base=3.1.0
- numpy=1.17.3
- pandas=0.25.2
- perl=5.26.2
- pycparser=2.19
- pyparsing=2.4.2
- r-base=3.5.1
- r-cli=1.1.0
- r-ggplot2=3.2.1
- r-lattice=0.20_38
- r-latticeextra=0.6_28
- r-matrix=1.2_17
- r-matrixstats=0.55.0
- r-plyr=1.8.4
- r-rcolorbrewer=1.1_2
- r-reshape2=1.4.3
- r-rlang=0.4.1
- r-stringi=1.4.3
- r-stringr=1.4.0
- r-utf8=1.1.4
- scipy=1.3.1
- biopython=1.77
- perl-bioperl=1.7.2
- circos=0.69.8
- bedtools=2.29.2
- vcftools=0.1.16
- plink=1.90b6.12
