name: base
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- blast=2.9.0
- fasttree=2.1.10
- iqtree=1.6.12
- mafft=7.310
- matplotlib=3.1.0
- matplotlib-base=3.1.0
- numpy=1.17.3
- pandas=0.25.2
- perl=5.26.2
- pycparser=2.19
- pyparsing=2.4.2
- r-base=3.5.1
- r-ggplot2=3.2.1
- r-matrix=1.2_17
- r-rcolorbrewer=1.1_2
- r-reshape2=1.4.3
- r-stringi=1.4.3
- r-stringr=1.4.0
- r-utf8=1.1.4
- scipy=1.3.1
- biopython=1.77
- perl-bioperl=1.7.2
- circos=0.69.8
- bedtools=2.29.2
- vcftools=0.1.16
- plink=1.90b6.12
