name: base
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- blast=2.9.0
- fasttree=2.1.10
- iqtree=1.6.12
- mafft=7.310
- matplotlib=3.1.0
- pandas=0.25.2
- perl=5.26.2
- pycparser=2.19
- pyparsing=2.4.2
- r-base=3.5.1
- r-ggplot2=3.2.1
- r-utf8=1.1.4
- circos=0.69.8
- bedtools=2.29.2
- vcftools=0.1.16
- plink=1.90b6.12
- r-cmplot=3.6.2
- admixture=1.3.0
