echo "######################################################"
echo "#      欢迎使用组学大讲堂提供的docker镜像            #"
echo "#      问题交流请访问：www.omicsclass.com            #"
echo "######################################################"
echo ""
echo "            Linux新手建议学习课程："
echo "      --> https://www.omicsclass.com/article/702"
echo ""
echo "         搭建实验室生信分析平台与docker使用详情见课程："
echo "      --> https://www.omicsclass.com/article/1181"

